/-
# Uwueave.Traces — one dependent pair (honest Zielonka step).

`Automata` §2 proves the **degenerate** trace alphabet: every pair of letters
commutes, so runs are permutation-invariant (`exec_perm`). Mazurkiewicz's
real theory is finer — words modulo an **independence relation** on a subset
of pairs — and Zielonka's theorem identifies the trace-closed regular
languages with deadlock-free asynchronous automata. Neither is formalized
here.

This file takes exactly **one honest step** past the degenerate case:

  * a **3-letter** alphabet `{a, b, c}`;
  * independence `a ∥ b`, `a ∥ c`, and **not** `b ∥ c` (one dependent pair);
  * trace equivalence = the smallest equivalence on words generated by
    swapping adjacent independent letters;
  * if an action family respects that independence, trace-equivalent words
    give the same `exec` result (the positive half);
  * reordering the dependent pair `b, c` changes the run of a concrete
    action on a concrete state (the negative half, by `decide`).

Under a **hypothetical** global-independence assumption (every pair
independent — false for this alphabet, see `not_full_independent`),
`TraceEq` collapses to `List.Perm` and the commuting-run theorem is
exactly `Automata.exec_perm`. That is the bridge, not a claim that this
file is full Mazurkiewicz / Zielonka.

## What is NOT formalized

  * Arbitrary independence alphabets / dependence graphs.
  * Zielonka's distributed construction or his characterization theorem.
  * Trace monoids, Foata normal form, lexicographic normal form.
  * Asynchronous automata, diamonds, or deadlock-freedom.
  * Infinite alphabets, continuous traces, or any topology.

Literature:
  * Mazurkiewicz — "Concurrent Program Schemes and their Interpretations",
    DAIMI PB-78, Aarhus, 1977.
  * Zielonka — "Notes on Finite Asynchronous Automata", RAIRO ITA 21(2), 1987.
  * Diekert, Rozenberg (eds.) — *The Book of Traces*, World Scientific, 1995.
-/
import Uwueave.Automata

namespace Uwueave.Traces

open Uwueave.Automata

universe u

/-! ## §1. The alphabet and the independence relation. -/

/-- Three letters: `a` is independent of both others; `b` and `c` depend. -/
inductive Letter where
  | a
  | b
  | c
  deriving DecidableEq, Repr, Inhabited

/-- **Independence** on the three-letter alphabet: `a ∥ b`, `a ∥ c`, and
neither `b ∥ c` nor `c ∥ b`. Reflexive pairs and the dependent pair are all
`False`. The relation is symmetric (`independent_symm`). -/
def Independent : Letter → Letter → Prop
  | .a, .b => True
  | .b, .a => True
  | .a, .c => True
  | .c, .a => True
  | _, _ => False

@[simp] theorem independent_ab : Independent .a .b := trivial
@[simp] theorem independent_ba : Independent .b .a := trivial
@[simp] theorem independent_ac : Independent .a .c := trivial
@[simp] theorem independent_ca : Independent .c .a := trivial

theorem not_independent_bc : ¬ Independent .b .c := fun h => h
theorem not_independent_cb : ¬ Independent .c .b := fun h => h
theorem not_independent_aa : ¬ Independent .a .a := fun h => h
theorem not_independent_bb : ¬ Independent .b .b := fun h => h
theorem not_independent_cc : ¬ Independent .c .c := fun h => h

/-- Independence is symmetric — required so the adjacent-swap generator is
an undirected step (and so `TraceEq.symm` can flip a `swap`). -/
theorem independent_symm {x y : Letter} (h : Independent x y) :
    Independent y x := by
  cases x <;> cases y <;> simp [Independent] at h ⊢ <;> exact h

/-- This alphabet is **not** globally independent: the dependent pair is the
whole point of the file. Global independence is used only as a hypothesis
that recovers `List.Perm` / `exec_perm` (see §3). -/
theorem not_full_independent : ¬ ∀ x y : Letter, Independent x y := by
  intro h
  exact not_independent_bc (h .b .c)

/-! ## §2. Trace equivalence.

Smallest equivalence on `List Letter` generated by swapping adjacent
independent letters. Constructor shape matches `List.Perm` so induction
against `exec` mirrors `Automata.exec_perm`; the only difference is that
`swap` is gated by `Independent`. -/

/-- **Trace equivalence**: words related by a sequence of adjacent swaps of
independent letters. `nil` / `cons` / `trans` as in `List.Perm`; `swap`
requires `Independent x y` and orients `y :: x :: l ~ x :: y :: l` exactly
as `List.Perm.swap` does without the gate. -/
inductive TraceEq : List Letter → List Letter → Prop where
  | nil : TraceEq [] []
  | cons (x : Letter) {l₁ l₂ : List Letter} :
      TraceEq l₁ l₂ → TraceEq (x :: l₁) (x :: l₂)
  | swap (x y : Letter) (l : List Letter) :
      Independent x y → TraceEq (y :: x :: l) (x :: y :: l)
  | trans {l₁ l₂ l₃ : List Letter} :
      TraceEq l₁ l₂ → TraceEq l₂ l₃ → TraceEq l₁ l₃

@[refl] theorem TraceEq.refl : ∀ l : List Letter, TraceEq l l
  | [] => .nil
  | x :: xs => (TraceEq.refl xs).cons x

theorem TraceEq.rfl {l : List Letter} : TraceEq l l := TraceEq.refl l

theorem TraceEq.symm {l₁ l₂ : List Letter} (h : TraceEq l₁ l₂) :
    TraceEq l₂ l₁ := by
  induction h with
  | nil => exact .nil
  | cons x _ ih => exact .cons x ih
  | swap x y l hindep => exact .swap y x l (independent_symm hindep)
  | trans _ _ ih₁ ih₂ => exact .trans ih₂ ih₁

/-- Adjacent independent letters may be swapped (oriented either way). -/
theorem TraceEq.swap_ab (l : List Letter) :
    TraceEq (.a :: .b :: l) (.b :: .a :: l) :=
  .swap .b .a l independent_ba

theorem TraceEq.swap_ba (l : List Letter) :
    TraceEq (.b :: .a :: l) (.a :: .b :: l) :=
  .swap .a .b l independent_ab

theorem TraceEq.swap_ac (l : List Letter) :
    TraceEq (.a :: .c :: l) (.c :: .a :: l) :=
  .swap .c .a l independent_ca

theorem TraceEq.swap_ca (l : List Letter) :
    TraceEq (.c :: .a :: l) (.a :: .c :: l) :=
  .swap .a .c l independent_ac

/-! ## §3. Full independence collapses to `List.Perm`.

If every pair were independent (false here — `not_full_independent`), every
`List.Perm` step is a `TraceEq` step, so the two relations agree. Combined
with `exec_traceEq` (§4) this recovers `Automata.exec_perm` as a corollary
(`exec_perm_of_fullIndep`): the degenerate alphabet of `Automata` §2 is the
full-independence special case of this file. -/

/-- Trace equivalence is always a permutation (each licensed swap is a perm
swap; the generators are a subset of `List.Perm`'s). -/
theorem traceEq_imp_perm {l l' : List Letter} (h : TraceEq l l') : l.Perm l' := by
  induction h with
  | nil => exact .nil
  | cons x _ ih => exact .cons x ih
  | swap x y l _ => exact .swap x y l
  | trans _ _ ih₁ ih₂ => exact .trans ih₁ ih₂

/-- **Under global independence**, every permutation is a trace equivalence:
the `swap` gate is always open, so induction on `List.Perm` lifts. -/
theorem traceEq_of_perm_of_fullIndep
    (hfull : ∀ x y : Letter, Independent x y)
    {l l' : List Letter} (h : l.Perm l') : TraceEq l l' := by
  induction h with
  | nil => exact .nil
  | cons x _ ih => exact .cons x ih
  | swap x y l => exact .swap x y l (hfull x y)
  | trans _ _ ih₁ ih₂ => exact .trans ih₁ ih₂

/-- Global independence ⇒ `TraceEq = List.Perm` (one direction is free). -/
theorem traceEq_iff_perm_of_fullIndep
    (hfull : ∀ x y : Letter, Independent x y)
    {l l' : List Letter} : TraceEq l l' ↔ l.Perm l' :=
  ⟨traceEq_imp_perm, traceEq_of_perm_of_fullIndep hfull⟩

/-! ## §4. Positive: independence-respecting actions are trace-invariant.

If independent letters commute as actions, every licensed adjacent swap
preserves the fold — so `TraceEq` words land on the same state. This is
`exec_perm` with the commutation hypothesis weakened from "all pairs" to
"independent pairs." -/

/-- **Trace-invariant execution.** An action family that commutes on every
independent pair yields the same `exec` result on trace-equivalent words.
Induction mirrors `Automata.exec_perm`; the `swap` case fires `hcomm` only
where `Independent` holds. -/
theorem exec_traceEq {S : Type u}
    (act : Letter → S → S)
    (hcomm : ∀ i j s, Independent i j → act i (act j s) = act j (act i s))
    {l l' : List Letter} (h : TraceEq l l') (base : S) :
    exec act base l = exec act base l' := by
  induction h generalizing base with
  | nil => rfl
  | cons i _ ih => exact ih (act i base)
  | swap i j l hindep =>
    -- `swap i j`:  j :: i :: l  ~  i :: j :: l, under `Independent i j`.
    simp only [exec_cons]
    rw [hcomm i j base hindep]
  | trans _ _ ih₁ ih₂ => exact (ih₁ base).trans (ih₂ base)

/-- **Bridge to `Automata.exec_perm` as a corollary.** Under global independence,
`List.Perm` lifts to `TraceEq` (`traceEq_of_perm_of_fullIndep`); full pairwise
commutation specializes the independence-gated hypothesis of `exec_traceEq`;
composing the two recovers permutation-invariance of `exec` without citing
`Automata.exec_perm`. This is what §2 of `Automata` already is: the trace
theory of a fully independent alphabet. -/
theorem exec_perm_of_fullIndep {S : Type u}
    (act : Letter → S → S)
    (hfull : ∀ x y : Letter, Independent x y)
    (hcomm : ∀ i j s, act i (act j s) = act j (act i s))
    {l l' : List Letter} (h : l.Perm l') (base : S) :
    exec act base l = exec act base l' :=
  exec_traceEq act (fun i j s _ => hcomm i j s)
    (traceEq_of_perm_of_fullIndep hfull h) base

/-! ## §5. A concrete family: `a` on the first component; `b`/`c` on the second.

State is a product so the independence geometry is visible: `a` touches only
the left coordinate (commutes with both `b` and `c`); `b` doubles and `c`
increments the right coordinate (they do **not** commute). -/

/-- Concrete actions on `Nat × Nat`:
  * `a` increments the left component;
  * `b` doubles the right component;
  * `c` increments the right component. -/
def depAct : Letter → Nat × Nat → Nat × Nat
  | .a, (x, y) => (x + 1, y)
  | .b, (x, y) => (x, 2 * y)
  | .c, (x, y) => (x, y + 1)

/-- `depAct` respects this alphabet's independence: on every pair that
`Independent` licenses, the two actions commute. -/
theorem depAct_respects_indep :
    ∀ i j s, Independent i j → depAct i (depAct j s) = depAct j (depAct i s) := by
  intro i j s h
  match i, j, s with
  | .a, .b, (_, _) => rfl
  | .b, .a, (_, _) => rfl
  | .a, .c, (_, _) => rfl
  | .c, .a, (_, _) => rfl
  | .a, .a, _ => cases h
  | .b, .b, _ => cases h
  | .c, .c, _ => cases h
  | .b, .c, _ => cases h
  | .c, .b, _ => cases h

/-- Positive witness: swapping the independent pair `a, b` is a `TraceEq`
step, so `exec` agrees (via `exec_traceEq`). -/
theorem independent_pair_same_exec :
    exec depAct (0, 0) [.a, .b] = exec depAct (0, 0) [.b, .a] :=
  exec_traceEq depAct depAct_respects_indep (TraceEq.swap_ab []) (0, 0)

/-- Unfolded values of the positive witness (sanity, not a new law). -/
theorem independent_pair_eval :
    exec depAct (0, 0) [.a, .b] = (1, 0) ∧
    exec depAct (0, 0) [.b, .a] = (1, 0) := by
  simp [exec, depAct]

/-! ## §6. Negative: the dependent pair is visible to `exec`.

`b` then `c` doubles then increments; `c` then `b` increments then doubles.
From `(0, 0)` the right components are `1` versus `2`. Trace theory refuses
to identify these words precisely because `¬ Independent b c`; the run
agrees with that refusal. -/

/-- **Dependent reordering changes the run.** Concrete state `(0, 0)`,
concrete actions `depAct`, words `[b, c]` and `[c, b]`: the results differ
(`decide`). This is the witness that partial independence is load-bearing —
full `exec_perm` would have forced equality. -/
theorem dependent_pair_reordering_changes_exec :
    exec depAct (0, 0) [.b, .c] ≠ exec depAct (0, 0) [.c, .b] := by
  decide

/-- The two runs, named: `b;c` lands at `(0, 1)`, `c;b` at `(0, 2)`. -/
theorem dependent_pair_eval :
    exec depAct (0, 0) [.b, .c] = (0, 1) ∧
    exec depAct (0, 0) [.c, .b] = (0, 2) := by
  simp [exec, depAct]

/-- Same clash under `depAct` for the right components alone, by `omega`. -/
theorem dependent_pair_right_components_differ :
    (exec depAct (0, 0) [.b, .c]).2 ≠ (exec depAct (0, 0) [.c, .b]).2 := by
  decide

end Uwueave.Traces
