/-
# Uwueave.Preo.ProjectionV1Fixtures — exact V1 generated-source fixtures

Closed string equalities and their six local recursion-limit allowances are
isolated here. Production validator and renderer imports never elaborate these
proof terms. Importing this module also imports `ProjectionV1Examples`, because
the fixtures deliberately reuse its named first-order values; it is therefore
a regression-test surface rather than a production dependency.
-/
import Uwueave.Preo.ProjectionV1Examples

namespace Uwueave.Preo.ProjectionV1

open Uwueave.Preo.Artifact

set_option autoImplicit false

namespace Examples

theorem rust_string_literal_fixture :
    FixtureHooks.stringLiteral "A\"\\\nλ" = "\"A\\\"\\\\\\u{a}\\u{3bb}\"" := by decide

/-- Decimal emission is not bounded by a Rust machine word. -/
theorem unbounded_decimal_fixture :
    FixtureHooks.decimal (2 ^ 100) = "\"1267650600228229401496703205376\"" := by decide

def emptyRustFixture : String := r###"// @generated by Uwueave.Preo.ProjectionV1.renderRustSource; do not edit.
// Validated first-order coordination data only; no verifier or permit API.

pub mod uwueave_preo_projection_v1 {
    pub const UWUEAVE_PREO_PROJECTION_V1_SCHEMA: &str = "uwueave/preo-projection/v1";

    #[derive(Clone, Copy, Debug, PartialEq, Eq)]
    pub enum UwueavePreoCurrencyV1 {
        PeerBarrier,
        ArbiterCut,
        NetworkRound,
        UserPrompt,
        Rollback,
    }

    #[derive(Clone, Copy, Debug, PartialEq, Eq)]
    pub enum UwueavePreoEvidenceKeyV1 {
        None,
        Named(&'static str),
    }

    #[derive(Clone, Copy, Debug, PartialEq, Eq)]
    pub struct UwueavePreoDemandV1 {
        pub currency: UwueavePreoCurrencyV1,
        pub participants_decimal: &'static [&'static str],
        pub scope_decimal: &'static str,
        pub epoch_decimal: &'static str,
        pub evidence: UwueavePreoEvidenceKeyV1,
        pub round_decimal: &'static str,
        pub barrier_decimal: &'static str,
    }

    #[derive(Clone, Copy, Debug, PartialEq, Eq)]
    pub enum UwueavePreoOriginV1 {
        Crossing { index_decimal: &'static str },
        Ambient,
    }

    #[derive(Clone, Copy, Debug, PartialEq, Eq)]
    pub struct UwueavePreoObligationV1 {
        pub origin: UwueavePreoOriginV1,
        pub demand: UwueavePreoDemandV1,
    }

    #[derive(Clone, Copy, Debug, PartialEq, Eq)]
    pub struct UwueavePreoDeclarationV1 {
        pub id_decimal: &'static str,
        pub state_type_id_decimal: &'static str,
        pub schema_version_decimal: &'static str,
    }

    #[derive(Clone, Copy, Debug, PartialEq, Eq)]
    pub struct UwueavePreoFieldV1 {
        pub id_decimal: &'static str,
        pub declaration_id_decimal: &'static str,
        pub kind_id_decimal: &'static str,
        pub carrier_type_id_decimal: &'static str,
        pub key_type_id_decimal: Option<&'static str>,
    }

    #[derive(Clone, Copy, Debug, PartialEq, Eq)]
    pub enum UwueavePreoVerdictEvidenceV1 {
        Free,
        Clash {
            left_words_decimal: &'static [&'static str],
            right_words_decimal: &'static [&'static str],
        },
    }

    #[derive(Clone, Copy, Debug, PartialEq, Eq)]
    pub struct UwueavePreoInvariantV1 {
        pub id_decimal: &'static str,
        pub declaration_id_decimal: &'static str,
        pub carrier_type_id_decimal: &'static str,
        pub verdict: UwueavePreoVerdictEvidenceV1,
    }

    #[derive(Clone, Copy, Debug, PartialEq, Eq)]
    pub struct UwueavePreoFutureV1 {
        pub id_decimal: &'static str,
        pub declaration_id_decimal: &'static str,
        pub world_type_id_decimal: &'static str,
        pub relation_id_decimal: &'static str,
    }

    #[derive(Clone, Copy, Debug, PartialEq, Eq)]
    pub struct UwueavePreoSessionV1 {
        pub id_decimal: &'static str,
        pub declaration_id_decimal: &'static str,
        pub crossings_decimal: &'static str,
        pub obligations: &'static [UwueavePreoObligationV1],
    }

    #[derive(Clone, Copy, Debug, PartialEq, Eq)]
    pub struct UwueavePreoProfileEntryV1 {
        pub currency: UwueavePreoCurrencyV1,
        pub value_decimal: &'static str,
    }

    #[derive(Clone, Copy, Debug, PartialEq, Eq)]
    pub struct UwueavePreoPlanV1 {
        pub id_decimal: &'static str,
        pub session_id_decimal: &'static str,
        pub actions: &'static [UwueavePreoDemandV1],
        pub profile: &'static [UwueavePreoProfileEntryV1],
    }

    #[derive(Clone, Copy, Debug, PartialEq, Eq)]
    pub struct UwueavePreoProjectionV1 {
        pub schema: &'static str,
        pub declaration: UwueavePreoDeclarationV1,
        pub fields: &'static [UwueavePreoFieldV1],
        pub invariants: &'static [UwueavePreoInvariantV1],
        pub futures: &'static [UwueavePreoFutureV1],
        pub sessions: &'static [UwueavePreoSessionV1],
        pub plans: &'static [UwueavePreoPlanV1],
    }

    pub static UWUEAVE_PREO_PROJECTION_V1: UwueavePreoProjectionV1 =
        UwueavePreoProjectionV1 {
            schema: UWUEAVE_PREO_PROJECTION_V1_SCHEMA,
            declaration: UwueavePreoDeclarationV1 { id_decimal: "1", state_type_id_decimal: "2", schema_version_decimal: "3" },
            fields: &[],
            invariants: &[],
            futures: &[],
            sessions: &[],
            plans: &[],
        };
}
"###

/-- Exact static-value fixture for the empty shape.  Even this degenerate case
must pass validation before the renderer implementation can be called. -/
theorem empty_projection_lines_fixture :
    FixtureHooks.projectionLines? emptyConfig emptyProjection = some
      ["    pub static UWUEAVE_PREO_PROJECTION_V1: UwueavePreoProjectionV1 =",
       "        UwueavePreoProjectionV1 {",
       "            schema: UWUEAVE_PREO_PROJECTION_V1_SCHEMA,",
       "            declaration: UwueavePreoDeclarationV1 { id_decimal: \"1\", state_type_id_decimal: \"2\", schema_version_decimal: \"3\" },",
       "            fields: &[],",
       "            invariants: &[],",
       "            futures: &[],",
       "            sessions: &[],",
       "            plans: &[],",
       "        };"] := by decide

/-- Exact nonempty row fixtures.  Together with
`renderer_fixture_validates`, these pin every V1 row family, both verdict tags,
nested demand/origin/evidence data, every stable reference, and the complete
five-currency profile in artifact order. -/
theorem renderer_declaration_rust_fixture :
    FixtureHooks.declaration rendererFixture.encoding.declaration =
      "UwueavePreoDeclarationV1 { id_decimal: \"100\", state_type_id_decimal: \"200\", schema_version_decimal: \"1\" }" := by
  rfl

set_option maxRecDepth 2000 in
theorem renderer_fields_rust_fixture :
    FixtureHooks.fields rendererFixture.encoding.fields =
      "&[UwueavePreoFieldV1 { id_decimal: \"101\", declaration_id_decimal: \"100\", kind_id_decimal: \"10\", carrier_type_id_decimal: \"200\", key_type_id_decimal: None }]" := by
  rfl

set_option maxRecDepth 4000 in
theorem renderer_invariants_rust_fixture :
    FixtureHooks.invariants rendererFixture.encoding.invariants =
      "&[UwueavePreoInvariantV1 { id_decimal: \"102\", declaration_id_decimal: \"100\", carrier_type_id_decimal: \"200\", verdict: UwueavePreoVerdictEvidenceV1::Free }, UwueavePreoInvariantV1 { id_decimal: \"106\", declaration_id_decimal: \"100\", carrier_type_id_decimal: \"201\", verdict: UwueavePreoVerdictEvidenceV1::Clash { left_words_decimal: &[\"1\", \"0\"], right_words_decimal: &[\"0\", \"1\"] } }]" := by
  rfl

set_option maxRecDepth 2000 in
theorem renderer_futures_rust_fixture :
    FixtureHooks.futures rendererFixture.encoding.futures =
      "&[UwueavePreoFutureV1 { id_decimal: \"103\", declaration_id_decimal: \"100\", world_type_id_decimal: \"200\", relation_id_decimal: \"300\" }]" := by
  rfl

set_option maxRecDepth 4000 in
theorem renderer_demand_rust_fixture :
    FixtureHooks.demand rendererDemand =
      "UwueavePreoDemandV1 { currency: UwueavePreoCurrencyV1::PeerBarrier, participants_decimal: &[\"0\", \"1\"], scope_decimal: \"7\", epoch_decimal: \"3\", evidence: UwueavePreoEvidenceKeyV1::Named(\"11\"), round_decimal: \"0\", barrier_decimal: \"5\" }" := by
  rfl

set_option maxRecDepth 6000 in
theorem renderer_obligation_rust_fixture :
    FixtureHooks.obligation ⟨.crossing 0, rendererDemand⟩ =
      "UwueavePreoObligationV1 { origin: UwueavePreoOriginV1::Crossing { index_decimal: \"0\" }, demand: UwueavePreoDemandV1 { currency: UwueavePreoCurrencyV1::PeerBarrier, participants_decimal: &[\"0\", \"1\"], scope_decimal: \"7\", epoch_decimal: \"3\", evidence: UwueavePreoEvidenceKeyV1::Named(\"11\"), round_decimal: \"0\", barrier_decimal: \"5\" } }" := by
  rfl

theorem renderer_session_reference_rust_fixture :
    FixtureHooks.session ⟨104, 100, 1, []⟩ =
      "UwueavePreoSessionV1 { id_decimal: \"104\", declaration_id_decimal: \"100\", crossings_decimal: \"1\", obligations: &[] }" := by
  rfl

set_option maxRecDepth 6000 in
theorem renderer_profile_rust_fixture :
    FixtureHooks.profile rendererProfile =
      "&[UwueavePreoProfileEntryV1 { currency: UwueavePreoCurrencyV1::PeerBarrier, value_decimal: \"1\" }, UwueavePreoProfileEntryV1 { currency: UwueavePreoCurrencyV1::ArbiterCut, value_decimal: \"0\" }, UwueavePreoProfileEntryV1 { currency: UwueavePreoCurrencyV1::NetworkRound, value_decimal: \"0\" }, UwueavePreoProfileEntryV1 { currency: UwueavePreoCurrencyV1::UserPrompt, value_decimal: \"0\" }, UwueavePreoProfileEntryV1 { currency: UwueavePreoCurrencyV1::Rollback, value_decimal: \"0\" }]" := by
  rfl

theorem renderer_plan_reference_rust_fixture :
    FixtureHooks.plan ⟨105, 104, [], []⟩ =
      "UwueavePreoPlanV1 { id_decimal: \"105\", session_id_decimal: \"104\", actions: &[], profile: &[] }" := by
  rfl


end Examples

end Uwueave.Preo.ProjectionV1
