#!/usr/bin/env bash
# Generate the lexical ⟨UNDONE…⟩ ledger, or fail if the checked-in copy drifted.

set -euo pipefail

usage() {
  cat <<'EOF'
Usage: scripts/undone-census.sh [--check]

With no arguments, regenerate docs/UNDONE.md.
With --check, compare docs/UNDONE.md with a fresh census and exit nonzero on drift.

UWUEAVE_UNDONE_CENSUS_ROOT may override the repository root for isolated tests.
EOF
}

case "${1:-}" in
  "") mode='write' ;;
  --check) mode='check' ;;
  -h|--help)
    usage
    exit 0
    ;;
  *)
    usage >&2
    exit 2
    ;;
esac

if (( $# > 1 )); then
  usage >&2
  exit 2
fi

script_dir=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)
default_repo_root=$(CDPATH='' cd -- "$script_dir/.." && pwd)
repo_root=${UWUEAVE_UNDONE_CENSUS_ROOT:-$default_repo_root}
repo_root=$(CDPATH='' cd -- "$repo_root" && pwd)
output="$repo_root/docs/UNDONE.md"
marker_re='⟨UNDONE(⟩|,|[[:space:]]|-|–|—)'

tmp_dir=$(mktemp -d "${TMPDIR:-/tmp}/uwueave-undone.XXXXXX")
trap 'rm -rf -- "$tmp_dir"' EXIT HUP INT TERM
expected="$tmp_dir/UNDONE.md"
sources="$tmp_dir/sources"

# Deliberately use the filesystem rather than `git ls-files`: an untracked new
# module must make --check fail before it can land without a ledger entry.
find "$repo_root/Uwueave" -type f -name '*.lean' -print \
  | LC_ALL=C sort > "$sources"

set --
while IFS= read -r source; do
  set -- "$@" "$source"
done < "$sources"

if (( $# == 0 )); then
  echo "undone-census: no Lean sources found under Uwueave/" >&2
  exit 1
fi

read -r marker_count block_count file_count < <(
  LC_ALL=C awk -v marker_re="$marker_re" '
    {
      marker_on_line = 0
      text = $0
      while (match(text, marker_re)) {
        marker_occurrences++
        marker_on_line = 1
        text = substr(text, RSTART + RLENGTH)
      }
      if (marker_on_line) {
        marker_lines++
        if (!seen_file[FILENAME]++) marker_files++
      }
    }
    END { print marker_occurrences + 0, marker_lines + 0, marker_files + 0 }
  ' "$@"
)

{
  printf '<!-- Generated by scripts/undone-census.sh; DO NOT EDIT. -->\n\n'
  printf '# ⟨UNDONE⟩ census\n\n'
  # These backticks are literal generated Markdown, not command substitutions.
  # shellcheck disable=SC2016
  printf '%s%s%s\n\n' \
    'This is a deterministic, lexical inventory of every `⟨UNDONE…⟩`-family ' \
    'marker in `Uwueave/**/*.lean`. Regenerate it with ' \
    '`scripts/undone-census.sh`; use `scripts/undone-census.sh --check` as a CI gate.'
  printf -- '- **Marker occurrences:** %s\n' "$marker_count"
  printf -- '- **Extracted blocks (marker-bearing source lines):** %s\n' "$block_count"
  printf -- '- **Lean files containing markers:** %s\n\n' "$file_count"
  # shellcheck disable=SC2016
  printf '%s\n\n' \
    'The matching grammar is the literal stem `⟨UNDONE` followed immediately by `⟩`, a comma, whitespace, or a dash (`-`, `–`, or `—`). Qualifier text and its closing `⟩` may continue onto later source lines. Identifier-like and punctuation substrings such as `⟨UNDONENESS⟩` and `⟨UNDONE.fake⟩` do not match.'
  printf 'Each block begins at one marker-bearing source line and includes its '
  printf 'following continuation lines up to the next blank line, list item, Markdown '
  printf 'heading, or Lean comment terminator. Two markers on one source line therefore '
  printf 'count as two occurrences but one extracted block. This ledger intentionally '
  printf 'includes definitions, quotations, inherited caveats, and references to older '
  printf 'items: it gates lexical drift, not the semantic status of the work.\n\n'

  LC_ALL=C awk -v root="$repo_root/" -v marker_re="$marker_re" '
    function close_block() {
      if (in_block) {
        print "````"
        print ""
        in_block = 0
      }
    }

    FNR == 1 {
      close_block()
      file_announced = 0
    }

    match($0, marker_re) {
      close_block()
      relative = substr(FILENAME, length(root) + 1)
      if (!file_announced) {
        print "## `" relative "`"
        print ""
        file_announced = 1
      }
      print "### [`" relative ":" FNR "`](../" relative "#L" FNR ")"
      print ""
      print "````text"
      print $0
      in_block = 1
      if ($0 ~ /-\//) close_block()
      next
    }

    in_block {
      if ($0 ~ /^[[:space:]]*$/ ||
          $0 ~ /^[[:space:]]*\*[[:space:]]/ ||
          $0 ~ /^[[:space:]]*#+[[:space:]]/ ||
          $0 ~ /^[[:space:]]*-\/[[:space:]]*$/) {
        close_block()
      } else {
        print $0
        if ($0 ~ /-\//) close_block()
      }
    }

    END { close_block() }
  ' "$@"
} > "$expected"

if [[ $mode == check ]]; then
  if [[ ! -f $output ]]; then
    echo "undone-census: docs/UNDONE.md is missing; regenerate it" >&2
    exit 1
  fi
  if ! cmp -s -- "$expected" "$output"; then
    echo "undone-census: docs/UNDONE.md is stale; regenerate it" >&2
    diff -u --label docs/UNDONE.md --label generated/UNDONE.md \
      "$output" "$expected" || true
    exit 1
  fi
  printf 'undone-census: current (%s markers, %s blocks, %s files)\n' \
    "$marker_count" "$block_count" "$file_count"
else
  mv -- "$expected" "$output"
  printf 'undone-census: wrote docs/UNDONE.md (%s markers, %s blocks, %s files)\n' \
    "$marker_count" "$block_count" "$file_count"
fi
